server:
  display-name: coletor

spring:

  main:
    banner-mode: "off"

  thymeleaf:
    mode: LEGACYHTML5

logging:
  file: ${user.home}/sigapi/logs/coletor.log

sigapi:
  coletor:
    diretorio: ${user.home}/sigapi/coletor
